name: Deploy

on:
  push:
    branches:
      - dev # Триггер для dev-сервера
      - main # Триггер для prod-сервера

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }} # Переменные из GitHub Secrets

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/project
            git pull origin ${{ github.ref_name }}
            docker-compose down
            docker-compose up --build -d
